# @package _global_

defaults:
  - _self_
  - data: famli # choose datamodule with `test_dataloader()` for evaluation
  - model: famli
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - callbacks: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /mnt/Enterprise2/AI-Sarosh/code-repo/logs/train/runs/2024-12-19_12-39-56/checkpoints/epoch_027.ckpt
